### ISSUE TITLE
Blank Web Console screen - Uncaught Runtime error

### ISSUE THREAD

**Issue by DPG7332** [google-gemini/multimodal-live-api-web-console#15]
### Description of the bug:

I followed the steps in this youtube video: https://www.youtube.com/watch?v=Qk3K7JdIebw (cloned the repo, created an env.local file, entered my API key, ran npm install, ran start,  and all looked well and in compiled successfully. However when I start the program, I get a blank web console screen. Just before  the screen goes blank, an error flashes on the webpage. The error says "Uncaught Runtime error". See attached screenshot. Also there is a type-o in the error. it says "set REACT_GEMINI_APIK_KEY in .env" not sure if that matters et all. 

![gemini_install](https://github.com/user-attachments/assets/c689a562-a1b5-47b4-be60-a1842bee367d)
![Unaught_runtime_error2](https://github.com/user-attachments/assets/de5e9b86-049c-4eca-9b8f-4593fb85f519)

**Comment by ViaAnthroposBenevolentia** [comment]
Try to put your API key in the .env file instead.

**Comment by DPG7332** [comment]
Thanks. What is the name of the .env file supposed to be? I had to create the env.local myself.
