### ISSUE TITLE
add a demo with no build requirement

### ISSUE THREAD

**Issue by AwokeKnowing** [google-gemini/multimodal-live-api-web-console#19]
### Description of the feature request:

Nothing here inherently requires any build at all. we could simply host a folder, and be done, with any code edits directly applying just by saving the file.

There is no need for typescript/tsx/scss/react.     They are not making the project shorter, easier, or anything. They are just a legacy chain of dependencies forcing a 'build' for no reason.

If you really want fancy 'components' you can use a library that is based on modern HTMLElement components which don't need a build.

### What problem are you trying to solve with this feature?

the problem is this app completely obscures the absolute simplicity of using the google api with a crufty old legacy buildchain.  The front end in particular should just be plain es modules and at most 3rd party component library that doesn't require build could be included.  As it is, it requires extra dependency and knowlege of React, Typescript, Scss, none of which are actual native web technology and none of which are providing significant value.  Sure a React/Typescript app may be populare, but a Javascript app is more appropriate as a demo and starting point for a wider variety of end results.

**Comment by hapticdata** [comment]
Hi! 
I understand the appeal of development using normal javascript modules, no build system and using web components; in fact I did release a small project for Gemini built that way - [right here](https://github.com/google-gemini/starter-applets/tree/main/maps), usable [here in AI Studio](https://aistudio.google.com/starter-apps/map).

For this particular project, we determined that react/typescript/npm was the approach we wanted to move forward with. If you would like to build your own Multimodal Live API - Web Console without any of this, I would encourage you to do so and it would be really cool to see it!

cheers!

**Comment by ViaAnthroposBenevolentia** [comment]
@AwokeKnowing, _**YAAYYY!!!**_ Here you go: [I did it!](https://github.com/ViaAnthroposBenevolentia/gemini-2-live-api-demo)

**Comment by ViaAnthroposBenevolentia** [comment]
@hapticdata, Sorry, can I ask a question? I implemented this in vanilla js but used this repository as a reference. I hope that I don't have to change my MIT license to APACHE 2.0 and then add a massive license chunks in every file as in your repo?

**Comment by peteryxu** [comment]
> I did it!

this is amazing: cloned your repo, and ran it without any issue in 20 sec -:)

**Comment by arthurwolf** [comment]
I so wish there was a simpler AI for this, I played with another "live voice" thing, and it's one import, two lines of code, and you're good. Why so complex, why so much code...
