### ISSUE TITLE
Tool or Conversation Logs don't work

### ISSUE THREAD

**Issue by sokart** [google-gemini/multimodal-live-api-web-console#23]
### Description of the bug:

By selecting the "Tool Usage" or "Conversations" from the upper left drop down menu nothing appears to the screen. Only the client/server logs are appeared.

**Comment by sokart** [comment]
The above holds only for the native tools such as google_search

**Comment by hapticdata** [comment]
Hi!
the `google_search` tool does not return any tokens to log. However the `code_execution` tool does.
I have added support for `executableCode` and `codeExecutionResult` parts [here](https://github.com/google-gemini/multimodal-live-api-web-console/commit/33a0a632ae54be7449f2c0e7028fa2f72a5760c3).

This should now include all parts you could receive in `text` or `audio` response modalities, logging works as expected.
