### ISSUE TITLE
App.tsx file Spelling mistakes

### ISSUE THREAD

**Issue by longmarchw** [google-gemini/multimodal-live-api-web-console#31]
### Description of the bug:

line 27，REACT_APP_GEMINI_APIK_KEY，Modified to: REACT_APP_GEMINI_API_KEY

### Actual vs expected behavior:

Spelling mistakes

**Comment by hapticdata** [comment]
[fixed](https://github.com/google-gemini/multimodal-live-api-web-console/commit/68bb998fdada9f14d120144a64cd15a3e0cf995a) thanks!
