### ISSUE TITLE
Use GEMINI_API_KEY environmental variable for the API key

### ISSUE THREAD

**Issue by rakyll** [google-gemini/multimodal-live-api-web-console#33]
### Description of the bug:

`GEMINI_API_KEY` is the canonical environmental variable across the Gemini API. The API users will have this key already set up in their environment. Use the same variable for consistency.

**Comment by hapticdata** [comment]
This is unfortunately a pattern from Create React App which the web console is based off of, all environment variables must start with `REACT_APP_`

https://create-react-app.dev/docs/adding-custom-environment-variables/
