### ISSUE TITLE
Highlight `npm start` as usage instructions

### ISSUE THREAD

**Issue by rakyll** [google-gemini/multimodal-live-api-web-console#34]
### Description of the feature request:

`multimodal-live-api-web-console` is primarily a playground project that users can clone and run, but it's not clear from the README how to run it until you scroll down to the "Available scripts" section buried under a bunch of other guidelines.

Add a section near to the top before anything else how to run the server:

## Usage

```sh
$ npm install && npm start

```

Runs the app in the development mode.
Open http://localhost:3000/ to view it in the browser.

**Comment by hapticdata** [comment]
[done](https://github.com/google-gemini/multimodal-live-api-web-console/commit/68bb998fdada9f14d120144a64cd15a3e0cf995a)! thanks
