### ISSUE TITLE
Problem using the multimodal-live-api-web-console, GenExprorer example

### ISSUE THREAD

**Issue by oscarcalvo** [google-gemini/multimodal-live-api-web-console#4]
### Description of the bug:

When I start the app all works well but it says 
13:51server.errorCould not connect to "wss://autopush-generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1alpha.GenerativeService.BidiGenerateContent?key=XXXXXXX"

Note I have set the api key

**Comment by machina-source** [comment]
In App.tsx if you remove `autopush-` from the host URL, that should fix it.

ex: `const host = "generativelanguage.googleapis.com";`

**Comment by oscarcalvo** [comment]
you are right @machina-source, I have seen your PR. thanks a lot
